#!/usr/bin/env python3
"""Preprocessing script for data/raw/official_event/yatsushiro/2026-08-13_0600_open_shelters.csv
Output: data/processed/yatsushiro_shelters_2026-08-13_0600_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/official_event/yatsushiro/2026-08-13_0600_open_shelters.csv"
dst = ROOT / "data/processed/yatsushiro_shelters_2026-08-13_0600_preprocessed.parquet"

# --- Load ---
df = pd.read_csv(src, encoding="utf-8-sig", low_memory=False)

# --- Select and rename columns ---
rename_map = {
    "shelter_number": "Shelter Number",
    "shelter_name": "Shelter Name",
    "district": "District",
    "maximum_capacity": "Maximum Shelter Capacity",
    "evacuee_households": "Evacuee Households",
    "evacuee_people": "Evacuees",
    "water_status_symbol": "Water Status",
    "shower_available_symbol": "Shower Availability",
    "temporary_toilets_installed": "Temporary Toilets Installed",
    "toilet_cars": "Toilet Cars",
    "observation_time": "Observation Time",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Shelter Number
df["Shelter Number"] = pd.to_numeric(df["Shelter Number"], errors="coerce")
# Shelter Name
df["Shelter Name"] = df["Shelter Name"].str.strip()
# District
df["District"] = df["District"].str.strip()
df["District"] = df["District"].astype("category")
# Maximum Shelter Capacity
df["Maximum Shelter Capacity"] = pd.to_numeric(df["Maximum Shelter Capacity"], errors="coerce")
# Evacuee Households
df["Evacuee Households"] = pd.to_numeric(df["Evacuee Households"], errors="coerce")
# Evacuees
df["Evacuees"] = pd.to_numeric(df["Evacuees"], errors="coerce")
# Water Status
df["Water Status"] = df["Water Status"].str.strip()
df["Water Status"] = df["Water Status"].astype("category")
# Shower Availability
df["Shower Availability"] = df["Shower Availability"].str.strip()
df["Shower Availability"] = df["Shower Availability"].astype("category")
# Temporary Toilets Installed
df["Temporary Toilets Installed"] = pd.to_numeric(df["Temporary Toilets Installed"], errors="coerce")
# Toilet Cars
df["Toilet Cars"] = pd.to_numeric(df["Toilet Cars"], errors="coerce")
# Observation Time
df["Observation Time"] = pd.to_datetime(df["Observation Time"], errors="coerce")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
