#!/usr/bin/env python3
"""Preprocessing script for data/raw/official_event/kumamoto_prefecture/2026-08-12_1400_municipality_shelter_totals.csv
Output: data/processed/kumamoto_prefecture_municipality_shelter_totals_2026-08-12_1400_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/official_event/kumamoto_prefecture/2026-08-12_1400_municipality_shelter_totals.csv"
dst = ROOT / "data/processed/kumamoto_prefecture_municipality_shelter_totals_2026-08-12_1400_preprocessed.parquet"

# --- Load ---
df = pd.read_csv(
    src,
    encoding="utf-8-sig",
    low_memory=False,
    dtype={"municipality_code": "string"},
)

# --- Select and rename columns ---
rename_map = {
    "observation_time": "Municipality Observation Time",
    "municipality_code": "Municipality Code",
    "municipality_japanese": "Municipality (Japanese)",
    "municipality_english": "Municipality",
    "open_shelters": "Open Shelter Count",
    "evacuees": "Evacuees",
    "source_report": "Source Report",
    "source_page": "Source Page",
    "evidence_level": "Municipality Evidence Tier",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
df["Municipality Code"] = df["Municipality Code"].str.zfill(5)

# --- Variable-level preprocessing ---
# Municipality Observation Time
df["Municipality Observation Time"] = pd.to_datetime(df["Municipality Observation Time"], errors="coerce")
# Municipality (Japanese)
df["Municipality (Japanese)"] = df["Municipality (Japanese)"].str.strip()
# Municipality
df["Municipality"] = df["Municipality"].str.strip()
df["Municipality"] = df["Municipality"].astype("category")
# Open Shelter Count
df["Open Shelter Count"] = pd.to_numeric(df["Open Shelter Count"], errors="coerce")
# Evacuees
df["Evacuees"] = pd.to_numeric(df["Evacuees"], errors="coerce")
# Source Report
df["Source Report"] = df["Source Report"].str.strip()
# Source Page
df["Source Page"] = pd.to_numeric(df["Source Page"], errors="coerce")
# Municipality Evidence Tier
df["Municipality Evidence Tier"] = df["Municipality Evidence Tier"].str.strip()
df["Municipality Evidence Tier"] = df["Municipality Evidence Tier"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
