#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01f/kumamoto_prefecture_shelter_master.parquet
Output: data/processed/kumamoto_prefecture_shelter_master_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01f/kumamoto_prefecture_shelter_master.parquet"
dst = ROOT / "data/processed/kumamoto_prefecture_shelter_master_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Shelter ID": "Shelter ID",
    "Shelter Name": "Shelter Name",
    "Address": "Address",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "Municipality Code": "Municipality Code",
    "Municipality": "Municipality",
    "Ward": "Ward",
    "Facility Type": "Facility Type",
    "Shelter Service Class": "Shelter Service Class",
    "Capacity Evidence Tier": "Capacity Evidence Tier",
    "Official Numeric Capacity": "Official Shelter Capacity",
    "Shelter Point Geometry": "Shelter Point Geometry",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Shelter ID
df["Shelter ID"] = df["Shelter ID"].str.strip()
# Shelter Name
df["Shelter Name"] = df["Shelter Name"].str.strip()
# Address
df["Address"] = df["Address"].str.strip()
# Latitude
df["Latitude"] = pd.to_numeric(df["Latitude"], errors="coerce")
# Longitude
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")
# Municipality Code
df["Municipality Code"] = df["Municipality Code"].str.strip()
# Municipality
df["Municipality"] = df["Municipality"].str.strip()
df["Municipality"] = df["Municipality"].astype("category")
# Ward
df["Ward"] = df["Ward"].str.strip()
df["Ward"] = df["Ward"].astype("category")
# Facility Type
df["Facility Type"] = df["Facility Type"].str.strip()
df["Facility Type"] = df["Facility Type"].astype("category")
# Shelter Service Class
df["Shelter Service Class"] = df["Shelter Service Class"].str.strip()
df["Shelter Service Class"] = df["Shelter Service Class"].astype("category")
# Capacity Evidence Tier
df["Capacity Evidence Tier"] = df["Capacity Evidence Tier"].str.strip()
df["Capacity Evidence Tier"] = df["Capacity Evidence Tier"].astype("category")
# Official Shelter Capacity
df["Official Shelter Capacity"] = pd.to_numeric(df["Official Shelter Capacity"], errors="coerce")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
