#!/usr/bin/env python3
"""Preprocessing script for data/raw/statistics/mhlw_ltc_2026_04/2604-h2-2_male.xlsx
Output: data/processed/mhlw_ltc_2026_04_male_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/statistics/mhlw_ltc_2026_04/2604-h2-2_male.xlsx"
dst = ROOT / "data/processed/mhlw_ltc_2026_04_male_preprocessed.parquet"

# --- Load the published total section (columns A:J, data from row 7) ---
logical_columns = [
    "都道府県", "保険者名", "要支援1", "要支援2", "要介護1",
    "要介護2", "要介護3", "要介護4", "要介護5", "合計",
]
df = pd.read_excel(src, header=None, skiprows=6, usecols="A:J", names=logical_columns)
df = df.loc[df["都道府県"].eq("熊本県") & df["保険者名"].notna()].copy()

# --- Select and rename columns ---
rename_map = {
    "\u90fd\u9053\u5e9c\u770c": "Prefecture",
    "\u4fdd\u967a\u8005\u540d": "Municipality",
    "\u8981\u652f\u63f41": "Support Level 1",
    "\u8981\u652f\u63f42": "Support Level 2",
    "\u8981\u4ecb\u8b771": "Care Level 1",
    "\u8981\u4ecb\u8b772": "Care Level 2",
    "\u8981\u4ecb\u8b773": "Care Level 3",
    "\u8981\u4ecb\u8b774": "Care Level 4",
    "\u8981\u4ecb\u8b775": "Care Level 5",
    "\u5408\u8a08": "Certified Total",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Prefecture
df["Prefecture"] = df["Prefecture"].str.strip()
# Municipality
df["Municipality"] = df["Municipality"].str.strip()
df["Municipality"] = df["Municipality"].astype("category")
# Support Level 1
df["Support Level 1"] = pd.to_numeric(df["Support Level 1"], errors="coerce")
# Support Level 2
df["Support Level 2"] = pd.to_numeric(df["Support Level 2"], errors="coerce")
# Care Level 1
df["Care Level 1"] = pd.to_numeric(df["Care Level 1"], errors="coerce")
# Care Level 2
df["Care Level 2"] = pd.to_numeric(df["Care Level 2"], errors="coerce")
# Care Level 3
df["Care Level 3"] = pd.to_numeric(df["Care Level 3"], errors="coerce")
# Care Level 4
df["Care Level 4"] = pd.to_numeric(df["Care Level 4"], errors="coerce")
# Care Level 5
df["Care Level 5"] = pd.to_numeric(df["Care Level 5"], errors="coerce")
# Certified Total
df["Certified Total"] = pd.to_numeric(df["Certified Total"], errors="coerce")

# --- Confirmed functional-support scopes ---
df["Higher Assistance Certified Population"] = df[
    ["Care Level 3", "Care Level 4", "Care Level 5"]
].sum(axis=1)
df["Care Certified Population"] = df[
    [f"Care Level {level}" for level in range(1, 6)]
].sum(axis=1)
df["Support or Care Certified Population"] = df[
    ["Support Level 1", "Support Level 2"]
    + [f"Care Level {level}" for level in range(1, 6)]
].sum(axis=1)
if df.isna().any().any():
    raise ValueError("Unexpected missing value in the selected Kumamoto insurer records")
if not df["Support or Care Certified Population"].eq(df["Certified Total"]).all():
    raise ValueError("Published certified total does not equal the seven reported levels")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
