#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01f/kumamoto_prefecture_shelter_capacity_sources.parquet
Output: data/processed/kumamoto_prefecture_shelter_capacity_sources_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01f/kumamoto_prefecture_shelter_capacity_sources.parquet"
dst = ROOT / "data/processed/kumamoto_prefecture_shelter_capacity_sources_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Official Source Record ID": "Capacity Source Record ID",
    "Source Municipality Code": "Municipality Code",
    "Source Municipality": "Municipality",
    "Source Facility Name": "Facility Name",
    "Source Address": "Address",
    "Official Capacity Primary (persons)": "Primary Official Capacity",
    "Official Capacity Primary Definition": "Primary Capacity Definition",
    "Official Capacity Secondary (persons)": "Secondary Official Capacity",
    "Official Capacity Secondary Definition": "Secondary Capacity Definition",
    "Official Building Area (m2)": "Official Building Area (m2)",
    "Earthquake Opening or Suitability Flag": "Earthquake Opening or Suitability Flag",
    "Earthquake Flag Definition": "Earthquake Flag Definition",
    "Official Source Title": "Official Source Title",
    "Official Source Date": "Official Source Date",
    "Official Source URL": "Official Source URL",
    "Official Source Page": "Official Source Page",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Capacity Source Record ID
df["Capacity Source Record ID"] = df["Capacity Source Record ID"].str.strip()
# Municipality Code
df["Municipality Code"] = df["Municipality Code"].str.strip()
# Municipality
df["Municipality"] = df["Municipality"].str.strip()
df["Municipality"] = df["Municipality"].astype("category")
# Facility Name
df["Facility Name"] = df["Facility Name"].str.strip()
# Address
df["Address"] = df["Address"].str.strip()
# Primary Official Capacity
df["Primary Official Capacity"] = pd.to_numeric(df["Primary Official Capacity"], errors="coerce")
# Primary Capacity Definition
df["Primary Capacity Definition"] = df["Primary Capacity Definition"].str.strip()
df["Primary Capacity Definition"] = df["Primary Capacity Definition"].astype("category")
# Secondary Official Capacity
df["Secondary Official Capacity"] = pd.to_numeric(df["Secondary Official Capacity"], errors="coerce")
# Secondary Capacity Definition
df["Secondary Capacity Definition"] = df["Secondary Capacity Definition"].str.strip()
df["Secondary Capacity Definition"] = df["Secondary Capacity Definition"].astype("category")
# Official Building Area (m2)
df["Official Building Area (m2)"] = pd.to_numeric(df["Official Building Area (m2)"], errors="coerce")
# Earthquake Opening or Suitability Flag
df["Earthquake Opening or Suitability Flag"] = df["Earthquake Opening or Suitability Flag"].astype("category")
# Earthquake Flag Definition
df["Earthquake Flag Definition"] = df["Earthquake Flag Definition"].str.strip()
df["Earthquake Flag Definition"] = df["Earthquake Flag Definition"].astype("category")
# Official Source Title
df["Official Source Title"] = df["Official Source Title"].str.strip()
# Official Source Date
df["Official Source Date"] = df["Official Source Date"].str.strip()
# Official Source URL
df["Official Source URL"] = df["Official Source URL"].str.strip()
# Official Source Page
df["Official Source Page"] = pd.to_numeric(df["Official Source Page"], errors="coerce")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
